services:
  mongodb:
    container_name: rockshaver-db
    image: mongo:5.0
    networks: 
      - skynet
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cypress
      - MONGO_INITDB_ROOT_PASSWORD=skills
    restart: unless-stopped
    ports:
      - "27017:27017"
      
  mongoxp:
    container_name: mongo-express
    image: mongo-express
    networks: 
      - skynet
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=cypress
      - ME_CONFIG_MONGODB_ADMINPASSWORD=skills
      - ME_CONFIG_MONGODB_URL=mongodb://cypress:skills@mongodb:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=cypress
      - ME_CONFIG_BASICAUTH_PASSWORD=skills
    links:
      - mongodb
    restart: unless-stopped
    ports:
      - "17017:8081"

  rockshaver-api:
    container_name: rockshaver-api
    image: papitodev/rockshaver-api:space
    networks:
      - skynet
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/rockshaver
    ports:
      - "3333:3333"
    restart: unless-stopped
    command: /bin/sh -c "npm run go"

  rockshaver-web:
    container_name: rockshaver-web
    image: papitodev/rockshaver-web:space
    networks:
      - skynet
    depends_on:
      - rockshaver-api
    ports:
      - "3000:3000"
    restart: unless-stopped

  rockshaver-mob:
    container_name: rockshaver-mob
    image: papitodev/rockshaver-mob:space
    networks:
      - skynet
    depends_on:
      - rockshaver-api
    ports:
      - "8100:8100"
    restart: unless-stopped

networks: 
  skynet:
    driver: bridge

